### ISSUE TITLE
add support to Django 3.0

### ISSUE THREAD

**Issue by domdinicola** [django-webtest/django-webtest#106]

**Comment by rossmechanic** [comment]
Have a third party library that uses webtest, so can't upgrade mine to 3 until this is upgrade to 3. Happy to help with the upgrade

**Comment by gawel** [comment]
looks like it works already https://github.com/django-webtest/django-webtest/pull/107

what's the problem ?

**Comment by gawel** [comment]
@rossmechanic in your issue you say that `django-webtest` use `django.utils.functional.curry()` but I cant find any

**Comment by rossmechanic** [comment]
That's my fault. Was inadvertently pinned to an old version of `django-webtest`. sorry about that

**Comment by gawel** [comment]
ok, no worries. I guess this can be closed then
