### ISSUE TITLE
For every request it generates a new session. Which makes impossible session or messages be any usefull

### ISSUE THREAD

**Issue by oduvan** [django-webtest/django-webtest#112]
I'm using it with pytest.

```
def test_submit_admin(django_app_factory, django_user_model):
    admin_client = django_app_factory(csrf_checks=False)
    admin_client.set_user(django_user_model.objects.get_or_create(
        email='admin@test.com',
        is_superuser=True,
        is_staff=True,
        defaults={'username': 'admin', 'password': 'admin'},
    )[0])

    ret = admin_client.get(reverse('admin-user-merge-to', kwargs={'uid': 2}))
    assert ret.status == '302 Found'
    ret = ret.follow()
    assert ret.status == '200 OK'
    ret.mustcontain('User &quot;randomuser&quot; does not have Scan To CAD Jobs')
```

I'm expecting this message from cookies, but it fails, because every new ret object has a new session, but the same authorized user

**Comment by gawel** [comment]
I dont think set_user initialize a session so it may be the cause of your failure.

Another possible cause is that you use a domain to set your cookie which is not the domain used to emulate the http call. So the cookie is not properly sent.

But webtest use a cookiestorage for years and this works fine.

**Comment by oduvan** [comment]
@gawel omg. You where right. The problem is with domain. Ad the issue was right in front of my face, when I trace it, and I've missed it somehow. Thank you.
