### ISSUE TITLE
Update how DjangoTestApp retrieves a session

### ISSUE THREAD

**Issue by shea-maykinmedia** [django-webtest/django-webtest#113]
In one of the projects I'm working on that uses this library we're overriding Django's sessions but it means that when we try to access the session then this line https://github.com/django-webtest/django-webtest/blob/master/django_webtest/__init__.py#L212 evaluates to `False` though we do want it to evaluate to `True` so all the code inside this if statement runs and gets the session.

I'm wondering if you have an idea about how this could be changed to handle this case?  Perhaps checking `SESSION_ENGINE` and `SESSION_COOKIE_NAME` are set or maybe a try/except statement?  I'd be happy to make a pull request if there are any suggestions.

**Comment by gawel** [comment]
hi,

it's probably ok to check SESSION_ENGINE / SESSION_COOKIE_NAME if they are not set by default (when django.contrib.sesssion is not installed). But I'm not sure it works like that.

**Comment by shea-maykinmedia** [comment]
Hi,

Sorry for taking a while to respond.  I had a chance to look into this and it seems that SESSION_ENGINE and SESSION_COOKIE_NAME will always be set unless explicitly set to `None` since they're defined in the global_settings file https://github.com/django/django/blob/2.2.20/django/conf/global_settings.py#L473

I took a look into how we could maybe handle the case I described and I saw in Django's test client they do this https://github.com/django/django/blob/main/django/test/client.py#L583 which makes me wonder if the `if` statement could be removed?  I'm not sure if there is a reason for having the `if` statement but if not we could just do something like this

```python
engine = import_module(settings.SESSION_ENGINE)
cookie = self.cookies.get(settings.SESSION_COOKIE_NAME, None)
if cookie:
    return engine.SessionStore(cookie)
return {}
```

**Comment by gawel** [comment]
I guess it's safe enough. People who don't need/use session will never use this property

**Comment by shea-maykinmedia** [comment]
Okay, I'll try to make a PR for this change soon.
