### ISSUE TITLE
Support for python 3.7

### ISSUE THREAD

**Issue by maradragan** [django-webtest/django-webtest#114]
As far as I can see the latest version of django-webtest (1.9.7) only supports python up to version 3.6.
Is there going to be soon a new version which also supports python 3.7?

Or can we also use django-webtest 1.9.7 with python 3.7?

**Comment by gawel** [comment]
it support 3.8 already. see https://github.com/django-webtest/django-webtest/pull/108

changes haven't been released yet but I think there's no problem using the current release with 3.7
