### ISSUE TITLE
Permission caching in `RemoteUserBackend` causes failure of custom logic

### ISSUE THREAD

**Issue by interDist** [django-webtest/django-webtest#123]
Django-Webtest's backend extends Django's `RemoteUserBackend` which, in turn, extends `ModelBackend`. That backend implements a `has_perm()` method, which caches the known permissions on the user object in question. 

https://github.com/django/django/blob/67d0c4644acfd7707be4a31e8976f865509b09ac/django/contrib/auth/backends.py#L100-L105

For a project I'm involved with this causes tests related to user authorizations to fail, because the project's custom backend logic does not have access to the required permissions anymore - as the cache contains an empty `set`.

I assume this is an unintentional consequence, since Django-Webtest's backend is only concerned with rewriting authentication logic and does not have any permission logic. But the MRO / inheritance causes the `has_perm` method to exist on this backend, satisfying the  condition:

https://github.com/django/django/blob/67d0c4644acfd7707be4a31e8976f865509b09ac/django/contrib/auth/models.py#L202-L214

Am I correct in my assumption? If yes, can the backend be modified to return `False` from `has_perm`, in case a different backend is already defined in `settings.AUTHENTICATION_BACKENDS` ?

**Comment by gawel** [comment]
Sorry but I have no idea. I've never really used django's permissions.

To me it seems that if has_perm return false it will solve nothing since the first backend is used to evaluate the permissions.

Webtest's backend is always first: https://github.com/django-webtest/django-webtest/blob/master/django_webtest/__init__.py#L288

**Comment by gawel** [comment]
Hm, I missed this line https://github.com/django/django/blob/67d0c4644acfd7707be4a31e8976f865509b09ac/django/contrib/auth/models.py#L210

You may be right

But, always returning false is not a good idea. You don't know if other backends should/can handle permissions.

An ugly option is... a monkey patch:

```
from django_webtest.backends import WebtestUserBackend

def has_perm(*args):
    return False

WebtestUserBackend.has_perm = has_perm
```
Can you check if it feets your needs ?

I can't think of a clean way to make this configurable/optionnal

**Comment by interDist** [comment]
There are two possible scenarios:

1. The project does not define an authentication backend. In this case, Django's default is `ModelBackend` (https://docs.djangoproject.com/en/4.0/ref/settings/#authentication-backends). Since Django-Webtest's backend extends the same, there is no harm in placing it as the first (and only, in this case) backend. But the permission logic should be left as default.

2. The project _does_ define an authentication backend. This backend possibly handles authentication and permissions. Injecting Django-Webtest's backend as the first one would interfere with the authentication (good for testing) and with the authorization (undesired). However, returning `False` from the `has_perm` method would solve the issue _in this case_, because Django would move on to the 2nd backend, which would handle the check as is in the normal course of action (that is, not under tests).

I think the solution would be to check in `_setup_auth_backend` if another backend is already defined within `settings.AUTHENTICATION_BACKENDS`. Then it would include a version of `WebtestUserBackend` which defines `has_perm` with `return False`.

**Comment by gawel** [comment]
Yeah you're totally right. But like I said this needs to be optional. At least for backward compat. I'm afraid this may break existing tests... (it may not but that's something i'd really like to avoid..)

Maybe an option is to take care of a settings value ? Like `settings.WEBTEST_AUTHENTICATION_BACKEND`
Default to the current backend. And you can set `WEBTEST_AUTHENTICATION_BACKEND = WebtestUserBackendWhithoutPermissons` ?

Or maybe just `WEBTEST_HANDLE_PERMISSIONS = False` ? Default to True

**Comment by gawel** [comment]
Go for it then. Can you provide a PR ? Ideally with new test(s) but at least that does not breaks existing tests
