### ISSUE TITLE
Help needed while setting cookie for DjangoTestApp

### ISSUE THREAD

**Issue by rajalokan** [django-webtest/django-webtest#25]
To get through authentication while writing testcases, I'm trying to set cookies for a webtest request. All I want is in my application I can get request.COOKIES.get(settings.settings.SESSION_COOKIE_NAME) i.e. cookies need to be passed.

Here is what I've done:

```
cj = cookielib.CookieJar(cookielib.DefaultCookiePolicy())
cj.set_cookie(cookielib.Cookie(
            version=1,
            name=settings.SESSION_COOKIE_NAME, value="yzvqlvqcr2fiy6nfgaeczsqbhyr77363",
            port='80', port_specified=True, domain="localhost", domain_specified=True,
            domain_initial_dot=True, path="/", path_specified=True, secure=True,
            expires=True, discard=True, comment=None, comment_url=None, rest=None
 ))
app = DjangoTestApp()
app.cookiejar = cj
app.get("/")
```

Can anyone please help in this. I can't use other auth backends as we use LDAP for authentication.

**Comment by bochecha** [comment]
Hi, I'm having trouble with cookies as well, did you end up figuring this out? Anybody else can help?

**Comment by gawel** [comment]
app.set_cookie should work

**Comment by bochecha** [comment]
@gawel ok, so that's what I was doing, which means my problem with sessions is something else. I'll open a new issue then, thanks.
