### ISSUE TITLE
Dependencies are not installed automatically

### ISSUE THREAD

**Issue by sirex** [django-webtest/django-webtest#28]
Currently `setup.py` uses distutils, distutils donsn't automatically install dependencies, dependencies are installed only if you use setuptools.

https://github.com/kmike/django-webtest/commit/ae7641bccada4dfd9b02df2c9cba6c2f57f626f9#commitcomment-8688136

**Comment by kmike** [comment]
This is fixed by https://github.com/django-webtest/django-webtest/pull/26.
