### ISSUE TITLE
Ability to test for missing pages

### ISSUE THREAD

**Issue by gergelypolonkai** [django-webtest/django-webtest#30]
I’d like to test for 404 errors (e.g. to simulate when a user tries to fetch a missing product entry); in this case, I get an AppError exception. With Django test client I can check response.status_code. Is it possible to do the same with WebTest?

**Comment by kharandziuk** [comment]
@gergelypolonkai please provide a sample of the desired code

**Comment by gergelypolonkai** [comment]
class FrontTest(WebTest):
        def test_missing_product(self):
            # Try to fetch a product page of a missing product ID
            # /products/9999 will ultimately return a 404 error page
            page = self.app.get('/products/9999')
            self.assertEquals(page.status_code, 404)

In this case, I get this:

    AppError: Bad response: 404 NOT FOUND (not 200 OK or 3xx redirect for http://localhost/products/9999)
    '<h1>Not Found</h1><p>The requested URL /products/9999 was not found on this server.</p>'

I guess django-webtest (or the upstream WebTest?) asserts that the GET operation will succeed, either if I intentionally fetch a missing page.

**Comment by kharandziuk** [comment]
I believe you can achieve the desired behavior with
`page = self.app.get('/products/9999', expect_errors=True,),`. For further research you can look hear: http://webtest.readthedocs.org/en/latest/api.html#webtest.app.TestApp.get

**Comment by gergelypolonkai** [comment]
Sorry for the late response. Yes, this is exactly what I needed, thank you for pointing it out for me!
