### ISSUE TITLE
MAINTAINERS WANTED

### ISSUE THREAD

**Issue by kmike** [django-webtest/django-webtest#36]
Hey all,

I like this project and want it to live, but unfortunately I don't have enough bandwidth to support django-webtest well. Please drop me (kmike84@gmail.com) an email if you want to help and step up as a maintainer.

**Comment by andybak** [comment]
Hi,

One thing I've done successfully recently is to move a couple of projects into their own Github organisation and invite a couple of contributors. 

It seemed to work as people are more willing to help out if they aren't taking sole responsibility.

It also makes it much simpler to change maintainers without needing to change the repo url. 

I'd suggest a group called django-webtest so the url would become: https://github.com/django-webtest/django-webtest

We did this recently for django-backup and just yesterday for django-admin-tools.

**Comment by kmike** [comment]
Hey @andybak - a good suggestion, I've created an organization and moved the repo.

**Comment by kmike** [comment]
Thanks @kharandziuk @codeinthehole @gawel @andriisoldatenko! I'm happy with you as a team; closing this ticket for now. Feel free to invite other people if they are interested and you think that's helpful.

**Comment by andriisoldatenko** [comment]
@kmike Thanks!
