### ISSUE TITLE
Options method uses wrong signature in calling `super()`

### ISSUE THREAD

**Issue by carljm** [django-webtest/django-webtest#47]
`DjangoTestApp.options` calls its `super` method with `(url, params, headers, extra_environ, status, **kwargs)`, but the actual signature of `TestApp.options` in webtest is `def options(self, url, headers=None, extra_environ=None, status=None, expect_errors=False, xhr=False):` -- note that there is no `params` in the signature.

This can cause a variety of problems when calling `options`, since due to the misalignment of the arguments none of `headers`, `extra_environ`, or `status` are passed correctly.

While fixing this, it may be reasonable to switch to using keyword arguments for all these `super` calls, to catch positional mismatch problems more quickly in the future.

**Comment by merwok** [comment]
@gawel This is fixed now?
