### ISSUE TITLE
Authentication is not working with admin and postgres

### ISSUE THREAD

**Issue by eviltnan** [django-webtest/django-webtest#49]
I'm trying to test django admin interface with django-webtest. My tests are okay under sqlite, but when i change the database to postgres, I get 302 redirect to a login page of admin.

test:

```
class TestInstrumentAdmin(MongoengineTestMixin, TransactionWebTest):
    def setUp(self):
        self.instrument = InstrumentFactory()
        self.user = SuperUserFactory()

    def test_change_instrument(self):
        url = reverse('admin:stock_instrument_change', args=(self.instrument.id,))
        response = self.app.get(url, user=self.user)
        self.assertEqual(response.status_code, 200, response)
```

factory:

```
class SuperUserFactory(UserFactory):
    username = factory.Sequence(lambda n: 'user%d' % n)
    email = factory.LazyAttribute(lambda x: faker.email())
    is_superuser = True
    is_staff = True

    @classmethod
    def _create(cls, model_class, *args, **kwargs):
        manager = cls._get_manager(model_class)
        result = manager.create(*args, **kwargs)
        result.set_password("test")
        result.save()
        return result

```

**Comment by gawel** [comment]
This is not really a bug. What is the location of this 302 ?

**Comment by gawel** [comment]
And are you sure that your user exists in postgres after using the factory ? I guess it's the real problem.

**Comment by eviltnan** [comment]
The location of 302 is login page for admin, which means the user is not authenticated. I checked right before executing the request, if the user is in the database, and it seems to be there. More than that, django testcase client with same code authenticates the user, so it excludes the possibility of the user wouldn't be saved by the factory.

**Comment by gawel** [comment]
I don't have a clue. Tests runs with postgres on travis and everything is fine there. https://travis-ci.org/django-webtest/django-webtest/jobs/124183451

**Comment by eviltnan** [comment]
I use django 1.9.5, postgres 9.4. One more special thing is that i set test database name over TEST:NAME field of the django DATABASES option. Maybe this breaks the thing somehow?

**Comment by gawel** [comment]
You can try to run the tests from a local clone:
```
psql -c 'create database django_webtest_tests;' -U youruser
```
Then:
```
tox -e py27-django19-postgres
```

**Comment by philgyford** [comment]
I'm having the same issue; it seemed to start after upgrading to Django 1.10, although no idea why that specifically would be the reason. I'm doing this (app and model names genericized):

    my_model = MyModelFactory()

    admin_user = User.objects.create_superuser('adminuser', 'test@example.org', 'password')

    change_url = reverse('admin:appname_modelname_change', args=[my_model.pk,])

    response = self.app.get(change_url, user=admin_user)

And `response` is a 302 to `/admin/login/?next=/admin/appname/modelname/1/change/`.

I've checked that `admin_user` exists in the database, and is a superuser. This, using Django's standard test client, works fine:

    # with my_model, admin_user and change_url as above:
    from django.test.client import Client
    c = Client()
    c.login(username='adminuser', password='password')
    response = c.get(change_url)

**Comment by philgyford** [comment]
I tried switching my tests to use SQLite but that didn't fix the problem, so maybe this is a different issue.

BUT, after poking around the django-webtest code, I thought of adding `'django_webtest.middleware.WebtestUserMiddleware'` to the `MIDDLEWARE` in the settings I use for testing, and that gets things working again.

Is this required in order to do `self.app.get(url, user=user)`?

**Comment by gawel** [comment]
I don't think so, this should be added to the setting at runtime

**Comment by philgyford** [comment]
Odd - if I `print` the contents of `settings.MIDDLEWARE` during a test that uses django-webtest, its middleware isn't included unless I explicitly add it in my settings.

**Comment by gawel** [comment]
So maybe this is not working: https://github.com/django-webtest/django-webtest/blob/master/django_webtest/__init__.py#L267

**Comment by philgyford** [comment]
Hmm, yes. It does do the `settings.MIDDLEWARE_CLASSES.append(webtest_auth_middleware)` but if I check `settings.MIDDLEWARE` in my test, `django_webtest.middleware.WebtestUserMiddleware` isn't in it.

**Comment by gawel** [comment]
So this is the problem: https://github.com/django-webtest/django-webtest/blob/master/django_webtest/__init__.py#L225

Can you check the value of ```self.app.middleware_setting_name``` ?

I guess we'd rather check the django version to use the real settings name instead of trying to guess it. Either way, those lines need to be improved

**Comment by philgyford** [comment]
Oh... I'm an idiot. I was using v1.7.8 and so it didn't have that check for Django 1.10's middleware setting. Now I've upgraded to django_webtest v1.8 it works fine. I'm really, really sorry to have wasted your time! Thanks for your patience.

**Comment by merwok** [comment]
@gawel This ticket can be closed.
