### ISSUE TITLE
Incompatible with django 1.10 MIDDLEWARE setting

### ISSUE THREAD

**Issue by karyon** [django-webtest/django-webtest#54]
django-webtest seems to be incompatible with the MIDDLEWARE setting in django 1.10, authentication does not work in most of my tests.

The problem is most likely that the middlewares in django_webtest/middleware.py are not in the new middleware format. it's probably enough to make the middlewares inherit from the new mixin, see https://docs.djangoproject.com/en/1.10/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware.

my workaround is to use the old MIDDLEWARE_CLASSES setting for now.

**Comment by karyon** [comment]
are there any maintainers around? i'd do a pull request if i had the feeling it had chances of being merged...

**Comment by kharandziuk** [comment]
Hey, I promise to review your PR:)

**Comment by karyon** [comment]
there is quite a bunch of test failures with django 1.10. not sure if i want to fix all of that :)

but i'm pretty sure i don't want to expend any extra time on support for ancient versions. how important is that for you? im talking about django < 1.8 (you're testing with django 1.2, seriously :) ) and python 2.6. support for django 1.7 ended nine months ago, for python 2.6 three years ago.

**Comment by kharandziuk** [comment]
@karyon in general I agree with you but... https://www.djangosites.org/stats/ – says that versions between 1.2 and 1.6 are quite popular. The open question: is this statistic accurate?

**Comment by karyon** [comment]
i heavily doubt it, according to that page there are 60% of django installations with python <=2.6 which i can't imagine. python 2.7 was released in 2010.

people running an ancient version of django can also run a old version of django-webtest, i don't see any problem with that.

besides, running old versions of django is a security risk, and i think the discussion should actually stop there.

**Comment by kharandziuk** [comment]
so, as a result. Please provide a PR which fix the middleware issue and with actual code we will decide what to do
