### ISSUE TITLE
Drop old Django version support

### ISSUE THREAD

**Issue by sergei-maertens** [django-webtest/django-webtest#55]
From #54 it's clear that maintaining compatibility with ancient versions of Django provides a burden and demotivates people to submit/fix PR's/tests.

I suggest dropping support for Django versions < 1.8, and following Django's support scheme. People stuck on old versions of Django can use older django-webtest versions that are compatible.

This would require shim code to be cleaned up, build config to be updated and a proper document that states wich version of django-webtest supports which Django versions.

This, in turn, would make it easier to add support for new Django versions (like in #54).

I'm willing to draw up a PR after work.

**Comment by kharandziuk** [comment]
I will merge your PR if you create it. @django-webtest/owners does anybody have anything to say a about this?

**Comment by kmike** [comment]
I'm fine with that. Probably it makes sense to do one more release before releasing a version which is not compatible with older djangos.

**Comment by gawel** [comment]
I'm not against dropping support for older python/django versions. But I don't see any benefits if things works. We just dropped django 1.2 support because it was broken/painful to fix but that's it.
