### ISSUE TITLE
Logging in doesn't work 

### ISSUE THREAD

**Issue by hujosh** [django-webtest/django-webtest#58]
Apparently, webtest can handle logging a user into the app. OK, does it...?
```

class IndexPage(WebTest):
    def setUp(self):
        User.objects.create_user(
            username='danu',
            password='test123',
        )
   def test_index_page_clicking_on_general_feedback(self):
        # The user goes to the index page...
        index = self.app.get('/', user='danu')
        self.assertTemplateUsed(index, "feedback/index.html")
```

But i'm not being logged in. I'm being redirected to the login page instead. What is happening? I know I have installed django webtest because my webtest tests worked before i added authentication to my application.

**Comment by gawel** [comment]
We also have some tests:

 https://github.com/django-webtest/django-webtest/blob/master/django_webtest_tests/testapp_tests/tests.py#L182

But those works. Don't know why yours don't.

**Comment by hujosh** [comment]
Do i need to put anything into my settings.py specifically for web-test(apart from in installed_apps?

**Comment by gawel** [comment]
No. You dont need to modify your settings, even INSTALLED_APPS

**Comment by hujosh** [comment]
I came back to this problem after not having had looked at it for a while. I instantly saw what was wrong: i was missing django.contrib.auth from my installed apps...
I was missing that because i'm using the stripped-down settings file that gets auto-generated by pydanny's cookie cutter template for a django package. I think that the way you have packaged your app is superior to danny's.  For all of django's instenec on 'independent apps', it doesn't make it very clear how you're supposed to achieve that.
