### ISSUE TITLE
[proposition] pytest fixture

### ISSUE THREAD

**Issue by dszmaj** [django-webtest/django-webtest#60]
Have you thought about making a fixture for pytest?

it would be extremely great to be able to use webtest like this
```python
@pytest.mark.django_db
def test_django(app):
    resp = app.get('/smth/', user='smone')
    form = resp.forms['main']
    form['some_field'] = 'smth'
    submitted = form.submit()
    assert submitted.status_int == 200
```

**Comment by gawel** [comment]
Already done that. It's simple:

```python
import pytest
import django_webtest

wtm = django_webtest.WebTestMixin()


@pytest.fixture(scope='function')
def app(request, db):
    request.addfinalizer(wtm._unpatch_settings)
    wtm._patch_settings()
    wtm.renew_app()
    return wtm.app
```

Not sure it should be added. Even if it's not intrusive (only require an entry point) it will require a conditional dependency to pytest. But maybe it's not a problem.

**Comment by dszmaj** [comment]
What do you mean by conditional dependency? I'm not sure I know what you have in mind.

**Comment by gawel** [comment]
You'll need to add pytest as a dependency (and I think nobody want that) or a ```try: import pytest; except ImportError: print('you need pytest installed')```. And linux distribution's maintainers usually hate that.

Maybe the best option is to create another small package like pytest.django-webtest just for this purpose. It can be hosted under the django-webtest organisation here on github.

**Comment by kmike** [comment]
I'm fine with adding built-in pytest support; pytest dependency could be optional - e.g. we can import pytest only in django_webtest.pytest, and not expose it in `__init__`.

**Comment by dszmaj** [comment]
I'm sure there is a better way. Celery is a pytest plugin itself for exemple so definitely there is some thoughtful way of making this work as pytest plugin without any of your concerns, let me investigate that and maybe I could pr something

**Comment by gawel** [comment]
@dszmaj not really https://github.com/celery/celery/blob/master/celery/contrib/pytest.py#L4

But if it's not a problem for @kmike then it's fine for me too.

**Comment by gawel** [comment]
@dszmaj are you working on it ? If not I'll give it a try.

**Comment by dszmaj** [comment]
I can do this next week, if you would like to do this now then there is no problem.

**Comment by merwok** [comment]
I’m going to add this fixture in my project, if it works well and I get some time I’ll send a PR.

**Comment by merwok** [comment]
No globals!

```python

import pytest


@pytest.fixture(scope='session')
def app_mixin():
    # See https://github.com/django-webtest/django-webtest/issues/64
    from django_webtest import WebTestMixin
    return WebTestMixin()


@pytest.yield_fixture
def app(app_mixin):
    app_mixin._patch_settings()
    app_mixin.renew_app()
    yield app_mixin.app

    app_mixin._unpatch_settings()
```

**Comment by merwok** [comment]
Updated snippet with extra envvars to make generated URLs use testserver as host instead of localhost:80!  (maybe #59 )

**Comment by gawel** [comment]
I thought localhost was already replaced by testserver in the last PR

May be we can add a pytest option for that --hostname=whatever

Another cool pytest option can be --webtest-url=http://xxx If this one is set webtest will use wsgiproxy2 to launch tests

**Comment by merwok** [comment]
I use the released version 1.8.0 (webtest 2.0.25), so I don’t know if a PR fixes that (which one?).

I prefer static config rather than command-line options, since I don’t want test output to change depending on an option.

**Comment by gawel** [comment]
https://github.com/django-webtest/django-webtest/pull/62

You can specify options in a (setup|pytest).cfg and override it from the command line when needed

**Comment by merwok** [comment]
Yes, I do that for default options like the verbosity level, but it doesn’t feel right that tests could succeed or fail depending on an option.  Configuring the WebTestMixin instance in code to use the same host as django’s test client seems better to me.

**Comment by merwok** [comment]
Yay for #62!  If you publish an rc I can test it and report.

**Comment by gawel** [comment]
I've created a PR at #67 

Feedback welcome

**Comment by merwok** [comment]
The fixture works super well!  The localhost vs testserver issue is fixed, and upstream webtest prints body on unexpected status.  I undertand that you named it ``django_app`` to follow recent pytest-django conventions, but I’m not a big fan of losing the ability to pass ``params`` a as positional argument.  Anyway it works!
