### ISSUE TITLE
Unable to login to Django admin

### ISSUE THREAD

**Issue by chrisspen** [django-webtest/django-webtest#61]
Should this work with Django's admin?

I tried to use your login example with my '/admin/', but even though the form submit appears to succeed and returns a 200 response, all subsequent GET requests still return the login page, implying I failed to login.

My test looks like:

    def test_login(self):

        username = 'test@mydomain.com'
        password = 'password'
        user, _ = User.objects.get_or_create(
            username=username,
            defaults=dict(
                email=username,
                is_superuser=True,
                is_staff=True,
                is_active=True,
            )
        )
        user.is_superuser = True
        user.set_password(password)
        user.save()

        form = self.app.get('/admin/myapp/').form
        form['username'] = user.username
        form['password'] = password
        response = form.submit().follow()
        print('response', response)
        self.assertEqual(response.status_int, 200)

I'm running my test via Django test runner management command like:

    python manage.py test myapp.WebTests.test_login

Also, is there anything like Django's builtin unittest Client.login() method to handle low-hanging-fruit operations like this, so it's not something I need to repeat all the time?

**Comment by sagarchalise** [comment]
For your second query, there is an `user` argument as shown in https://github.com/django-webtest/django-webtest#usage

`self.app.get(URL, user=USERNAME)`

**Comment by gawel** [comment]
Check #58 If it doesn't work, the problem must be in your app/settings

**Comment by chrisspen** [comment]
Ah, I see. I didn't realize webtest doesn't have a persistent state like Django's Client(). You're right, passing in user fixes the problem, thanks.

**Comment by kmike** [comment]
@chrisspen django-webtest has persistent state

**Comment by chrisspen** [comment]
It doesn't appear to. After logging in as a user, subsequent requests that don't explicitly pass in a user are treated as an anonymous user with a brand new session.

**Comment by kmike** [comment]
I'm not sure why it happens, but there are [tests](https://github.com/django-webtest/django-webtest/blob/be09f6944de849cb16ec4e56629eae4a86be1632/django_webtest_tests/testapp_tests/tests.py#L182) for logging in by submitting a form using django-webtest. It looks like a bug if this doesn't work.

**Comment by chrisspen** [comment]
None of those tests seem to span more than a single request. To my point, a single login request succeeds, but unless I explicitly pass in my state (e.g. the user parameter) for every single request afterwards, the app doesn't remember the logged in user session.

**Comment by gawel** [comment]
@chrisspen webtest store cookies (and django use cookies to identify a session). I've used this feature more than once. It may not work if you have a weird cookie configuration. Like "cookie is only for mydomain.tld" while webtest use http://localhost. In that case you should have a specific settings to run your tests

**Comment by kmike** [comment]
It looks like an old issue https://github.com/django-webtest/django-webtest/issues/22, but I haven't seen it myself, and I also used this feature heavily. Something is not right here; a reproducable example could help debugging it.

**Comment by gawel** [comment]
Just added a test to assume it works: https://github.com/django-webtest/django-webtest/commit/e0a581bdaaeca91809297e8e2f5775b950239234
But I may have found a bug. resp.context is None at the second request.
