### ISSUE TITLE
Importing django_webtest should not cause access of django.conf.settings

### ISSUE THREAD

**Issue by merwok** [django-webtest/django-webtest#64]
Hello!  In my config, a pytest_configure hook defines environment variables (for database URL, secret key, etc.) before calling django.setup (which imports my settings module).

The body of WebTestMixin accesses settings.MIDDLEWARE, which raises ImproperlyConfigured('Requested setting MIDDLEWARE, but settings are not configured. [etc]',)
I work around by importing WebTestMixin inside a pytest session-scoped fixture (see #60 ). 

Can you use other code to detect whether MIDDLEWARE or MIDDLEWARE_CLASSES is the right thing to use?  Or move the existing code into a (cached) property?

**Comment by gawel** [comment]
I guess a property or a method to get the correct name would be fine

**Comment by merwok** [comment]
Super!  Thanks for fixing this.
