### ISSUE TITLE
Better error reporting for unexpected 400 status

### ISSUE THREAD

**Issue by merwok** [django-webtest/django-webtest#65]
During development, tests will fail when the app returns Bad Request instead of the expected 200 or 201 code.  The error message from webtest only shows that 400 != 200, but with django forms or django-rest-framework validators, there is more information in the response body, but it’s not displayed.

Current workflow: change the test to have status=400 and print response.body.

Desired change: Define DjangoTestApp._check_status:

```python

    def _check_status(self, status, res):
        if status is not None and status != res.status_int:
            msg = 'Bad response: {} (not {})\n{}'.format(res.status, status, res.body)
            raise webtest.AppError(msg)
        super(DjangoTestApp, self)._check_status(status, res)
```

(Code adapted from https://stackoverflow.com/questions/13505778/finding-the-real-error-in-a-webtest-test-failure ; res.body shows all headers and response bytes, which always works compared to res.json for example)

**Comment by gawel** [comment]
This should probably be added in webtest. _check_status is more complex than that and your code don't take care of cases like status="3*"

**Comment by merwok** [comment]
That’s true!  In my opinion the status code is part of the API, and 303 has a different role than 301 for example, so I test for exact codes and not ranges.  I’ll move this change request upstream.
