### ISSUE TITLE
Support authentication for django-rest-framework

### ISSUE THREAD

**Issue by merwok** [django-webtest/django-webtest#74]
Hello!  django-rest-framework uses its own authentication system, so calling `set_user` or `get(url, user=...)` has no effect for drf views that need authentication.

I am writing a custom drf auth backend that will work with the WEBTEST_USER header, and configure my settings manually to have it used.  Would you be interested in that class + an option to make WebTestMixin patch it in automatically?

**Comment by gawel** [comment]
We can give it a try if it doesn't require a lot of specific code. But maybe a third-party packages is better. Of course you can add a link to the package in django-webtest's readme.

**Comment by merwok** [comment]
The code is only this:

```python
# rest_framework_auth.py
from rest_framework.authentication import BaseAuthentication

class PassthroughAuthentication(BaseAuthentication):
    def authenticate(self, request):
        user = getattr(request._request, 'user', None)
        if user and user.is_active:
            return (user, None)


# settings.py, to be moved to WebTestMixin._patch_settings
REST_FRAMEWORK['DEFAULT_AUTHENTICATION_CLASSES'].extend([
    'rest_framework_auth.PassthroughAuthentication',
])
```

**Comment by gawel** [comment]
How do you plan to enable it ? iif rest_framework is installed ?

**Comment by merwok** [comment]
The setting `REST_FRAMEWORK` is a simple dict containing strings, nothing is imported or executed if rest_framework is not enabled for the app, so _patch_settings could always define the setting.

**Comment by gawel** [comment]
Ok. Looks good to me

**Comment by merwok** [comment]
DRF is adding support for authn based on REMOTE_USER, which will make my small class obsolete:
https://github.com/encode/django-rest-framework/pull/5306/files

Do you think there is value in adding my code to the docs in the meantime, or should we just close this ticket?

**Comment by sloria** [comment]
Thanks @merwok for the above snippet; it worked for me. It would be convenient to have this built-in, but I understand the maintainers' hesitation to support this OOB. DRF is a 3rd-party, albeit a very popular one.

**Comment by gawel** [comment]
I just forgot this issue, sorry. Will it be enough to add this in the doc ? Seems a really simple snippet.

**Comment by sloria** [comment]
@gawel Yeah, adding it to the docs seems like a good idea.

**Comment by merwok** [comment]
Please see my latest comment with a much shorter snippet (but untested!)

**Comment by sloria** [comment]
@merwok Thanks, I'll give that a try later today.

**Comment by sloria** [comment]
Yep, it worked!

```python
# core/settings/test.py
from rest_framework.authentication import RemoteUserAuthentication

class WebTestAuthentication(RemoteUserAuthentication):
    header = 'WEBTEST_USER'

AUTHENTICATION_BACKENDS.insert(0, 'django.contrib.auth.backends.RemoteUserBackend')
REST_FRAMEWORK['DEFAULT_AUTHENTICATION_CLASSES'].insert(0, 'core.settings.test.WebTestAuthentication')

```

**Comment by merwok** [comment]
Now my 5-line class seems way too big!

**Comment by merwok** [comment]
@gawel Should this become a doc patch only, or okay to add the code to make things work with zero config?

**Comment by gawel** [comment]
I think it's better to add this to the readme since it will require to have rest_framework installed

**Comment by merwok** [comment]
Rather, it will have no effect if rest_framework is not installed.  We can modify _patch_settings to include the necessary config (it’s only a dict with strings), and nothing will be imported if rest_framework is not already installed.

**Comment by gawel** [comment]
Ok then. But I don't see how you'll do that without a try/except ImportError

**Comment by merwok** [comment]
I don’t need a try/except since I’m not importing WebTestAuth, it’s rest_framework that does that from the string settings.

In `django_webtest/__init__.py`, I would edit _patch_settings to add or edit the strings needed to configure drf.

In `django_webtest/rest_framework.py`, I would import the BaseAuthentication class from rest_framework.  This submodule will not be imported if a project uses webtest_django without rest_framework.

**Comment by merwok** [comment]
In the end, I changed my five-line class (that checked `request._request.user`) for a different short class:

```python

class WebTestAuthentication(BaseAuthentication):
    """Auth backend for tests that use webtest."""
    header = 'WEBTEST_USER'

    def authenticate(self, request):
        value = request.META.get(self.header)
        if value:
            user = authenticate(django_webtest_user=value)
            if user and user.is_active:
                return (user, None)
```

with these settings:
```python
 if ENVIRONMENT == 'tests':
    REST_FRAMEWORK['DEFAULT_AUTHENTICATION_CLASSES'] = [
        'myapp.users.authentication.APITokenAuthentication',
        'myapp.users.authentication.WebTestAuthentication',
    ]
```

I don’t need to change the base django settings patched by django-webtest.

**Comment by gawel** [comment]
Thanks for the PR (and sorry I never replied to your last message)

**Comment by merwok** [comment]
No problem!  I copied my class in a bunch of projects and was not blocked.
