### ISSUE TITLE
Calling a get/put/etc method with user=None is not equivalent to set_user=None

### ISSUE THREAD

**Issue by merwok** [django-webtest/django-webtest#75]
Hello!  I found a small inconsistency that’s mildly inconvenient.

Context: In a project where 90% of the views require authentication, I define a simple `app` fixture that calls `django_app.set_user('bill@example.ca')` and returns that testapp object.  For tests that check that the open views are indeed open, or that a specific view is indeed restricted (which is needed to make sure custom permissions work as intended with rest-framework for example), I can either use the base `django_app` fixture, or use my `app` and start the test with `app.set_user(None)` to remove `WEBTEST_USER` from the WSGI environment.

I found myself changing some tests to use a consistent style (pass `user=user2` or `user=None` everywhere instead of calling set_user in a few cases), and that did not reset the user.

Proposed fix: in `_update_environ`, use a sentinel object instead of None to determine if the `user` parameter was given or not; if it is None, remove `WEBTEST_USER`.

**Comment by gawel** [comment]
LGTM

**Comment by merwok** [comment]
Can I make a second commit to make `user` mandatory in `set_user`?  In my opinion the call `app.set_user()` (currently valid) looks weird, whereas `app.set_user(None)` has a clear meaning.

**Comment by gawel** [comment]
Yep, seems legit

**Comment by merwok** [comment]
PR is open!
