### ISSUE TITLE
AttributtError if MIDDLEWARE is empty

### ISSUE THREAD

**Issue by bmihelac** [django-webtest/django-webtest#81]
`middleware_setting_name` [method](https://github.com/django-webtest/django-webtest/blob/master/django_webtest/__init__.py#L283-L293) checks if attribute `MIDDLEWARE` exists in settings and that it is truthy. 

 Empty list or None (which is default) `MIDDLEWARE` would not pass meaning middleware name would be from there `MIDDLEWARE_CLASSES` . This raises `AttributeError: 'Settings' object has no attribute 'MIDDLEWARE_CLASSES'`. 

Let me know if PR or test case is needed.

**Comment by gawel** [comment]
Hi. I believe it require both ? :)

**Comment by bmihelac** [comment]
OK, I'll create both. 

This *issue* has been introduced in this commit:

https://github.com/django-webtest/django-webtest/commit/48be2d55b9c54d1c20722e9a6aae699b69b958a1

I believe there it should be enough that `MIDDLEWARE` exists in settings this is *right* settings name.  Sounds good?

**Comment by gawel** [comment]
MIDDLEWARE_CLASSES is used by old django versions. So.. it may be more tricky than that.

An option is to check django version with setuptools (`pkg_resource.get_distribution('django').version`)
This maybe useful for other stuff.

Unit tests should tell you if you do it wrong, hopefully... :)

**Comment by bmihelac** [comment]
Failing test and fix in https://github.com/django-webtest/django-webtest/pull/82
Please let me know if you think that something else is needed regarding this.

**Comment by gawel** [comment]
LGTM, thanks
