### ISSUE TITLE
1.9.3 middleware error

### ISSUE THREAD

**Issue by cazino** [django-webtest/django-webtest#84]
Since 1.9.3 was relased some test can break in django 1.11:
 
```python
def _patch_settings(self):
        '''
            Patches settings to add support for django-webtest authorization
            and (optional) to disable CSRF checks.
            '''
        self._DEBUG_PROPAGATE_EXCEPTIONS = settings.DEBUG_PROPAGATE_EXCEPTIONS
>       self._MIDDLEWARE = self.settings_middleware[:]
E       TypeError: 'NoneType' object has no attribute '__getitem__'
```

The context is a django application compatible with 1.11 but whose settings still uses the MIDDLEWARE_CLASSES setting.

This commit broke it : https://github.com/django-webtest/django-webtest/pull/82/commits/7c8b821c135281cf76020e9ab1455b460516bb3b

I don't fully understand the purpose of this commit since by default, whatever the settings are,
hasattr(settings, 'MIDDLEWARE') will return True.

It's seems to me that this commit basically dropped the  MIDDLEWARE_CLASSES support.

**Comment by cazino** [comment]
Sorry for the bad formating of the stacktrace.

**Comment by gawel** [comment]
yeah, hasattr sucks. I guess `getattr(settings, 'MIDDLEWARE', None) is not None` should work. Can you check that ? (and even better submit a PR .. :) )

**Comment by cazino** [comment]
Yes it works, good catch.
On my way to submit a PR.

**Comment by cazino** [comment]
PR submitted !

**Comment by libcthorne** [comment]
I'm running into the same problem on Django 1.11.16 / django-webtest 1.9.3.

**Comment by gawel** [comment]
Just merged. Sorry for the lag..
