### ISSUE TITLE
 Specify parameters with `__init__` of WebTest.TestApp

### ISSUE THREAD

**Issue by mtb-beta** [django-webtest/django-webtest#86]
Currently, extra_environ and relative_to are specified in `__init__` of TestApp.

webtest can also specify the following parameters:

use_unicode, cookiejar, parser_features,　json_encoder, lint

```
    def __init__(self, app, extra_environ=None, relative_to=None,
                 use_unicode=True, cookiejar=None, parser_features=None,
                 json_encoder=None, lint=True):
```
https://github.com/Pylons/webtest/blob/master/webtest/app.py#L145-L147

I want to specify these.

# reason

In django_webtest 1.9 and later, HTTP_HOST is forcibly rewritten to testserver.

WebTest's default cookie policy does not accept cookies from testserver.

Therefore, django_webtest can not test functions using cookies.

If django_webtest can set cookiejear in TestApp, this problem will be solved.

Since it is expected that there are other problems that can not pass parameters to `__init__` of TestApp, it is better that django_webtest can set it in the same way.

**Comment by surfer190** [comment]
Yip, I have also noticed this.

Say you set the `app` with `extra_environ`:

```
        self.app = DjangoTestApp(
            extra_environ={'HTTP_HOST': self.tenant.domain_url}
        )
```

When making a request (`self.app.get(...)`) the host is reset to `testserver`.
So you have to set it on every request:
```

        response = self.app.get(
            reverse('entries:create'),
            user=self.user1,
            extra_environ={'HTTP_HOST': self.tenant.domain_url}
        )
```

or create a new app class and override each HTTP method, method to use the environ set on the clients `extra_environ`
