### ISSUE TITLE
request.data is a dict instance when using django_webtests app.post(), but a QueryDict instance when using curl

### ISSUE THREAD

**Issue by schumannd** [django-webtest/django-webtest#90]
I have explained the issue [on SO](https://stackoverflow.com/questions/53206284/django-views-when-is-request-data-a-dict-vs-a-querydict)

Is this an issue that should be fixed by django-webtest?

**Comment by gawel** [comment]
I guess params are sent via query string. just use post_json https://docs.pylonsproject.org/projects/webtest/en/latest/testapp.html#making-json-requests

**Comment by schumannd** [comment]
It is the other way around. I am testing using json, but clients are sending using `application/x-www-form-urlencoded`. My fault
