### ISSUE TITLE
extra_environ defaults not added to request

### ISSUE THREAD

**Issue by jon-armstrong** [django-webtest/django-webtest#94]
I've tried following the example from the Usage section but when I add header values to the `extra_environ` dictionary, they don't seem to be added to subsequent requests as the documentation suggests.

```
class MyTest(django_webtest.WebTest):
    extra_environ = {
        'HTTP_HOST': 'api',
        'HTTP_USER_AGENT': 'test'
    }
```

I've also tried reinitializing the test app in my test's setup method:
```
    def setUp(self):
        self.app = django_webtest.DjangoTestApp(
            extra_environ={'HTTP_HOST': 'api', 'HTTP_USER_AGENT': 'test'}
        )
```

However, it does work when passing `extra_environ` to `get()` etc, though this gets repetitive with a large number of tests.

**Comment by gawel** [comment]
That's weird. There's a test here: https://github.com/django-webtest/django-webtest/blob/master/django_webtest_tests/testapp_tests/tests.py#L324

**Comment by jon-armstrong** [comment]
This turned out to be an incompatibility with [django-hosts](https://github.com/jazzband/django-hosts) which I was also using.
