### ISSUE TITLE
django_webtest.rest_framework is broken on python2

### ISSUE THREAD

**Issue by bdauvergne** [django-webtest/django-webtest#98]
On a django project using DRF it breaks with

`E           ImportError: Could not import 'django_webtest.rest_framework.WebtestAuthentication' for API setting 'DEFAULT_AUTHENTICATION_CLASSES'. ImportError: cannot import name authentication.
`

Because you cannot import rest_framework from a module named rest_framework (it's resolved in local directory).

**Comment by merwok** [comment]
The fix is simpler that a rename: add `from __future__ import absolute_imports` to the module that contains the import.

**Comment by bdauvergne** [comment]
@merwork: I used your advice

**Comment by bdauvergne** [comment]
Fixed by #101
